Path Update: spiderMath_JUnit -> spiderMath_JUnit4

diff --git a/tacoco-diagnoses b/tacoco-diagnoses
--- a/tacoco-diagnoses
+++ b/tacoco-diagnoses
@@ -11,7 +11,7 @@ then
 fi
 
 cd $tacoco_home/projects4testing/spiderMath_Gradle && gradle build
-cd $tacoco_home/projects4testing/spiderMath_JUnit && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
+cd $tacoco_home/projects4testing/spiderMath_JUnit4 && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
 cd $tacoco_home/projects4testing/spiderMath_TestNG && mvn clean compile test-compile -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
 
 cd $tacoco_home
@@ -23,19 +23,19 @@ then
     exit 1
 fi
 
-mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/projects4testing/spiderMath_JUnit -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_JUnit -Danalyzer.opts="configs/tacoco-analyzer.config"
-
-if [ $? -ne 0 ];
-then
-    echo "Tacoco failed with spiderMath_JUnit..."
-    exit 1
-fi
-
 mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/projects4testing/spiderMath_TestNG -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_TestNG -Danalyzer.opts="configs/tacoco-analyzer.config" 
 
 if [ $? -ne 0 ];
 then
     echo "Tacoco failed with spiderMath_TestNG..."
+    exit 1
+fi
+
+mvn exec:java -Plauncher -Dtacoco.sut=$(pwd)/projects4testing/spiderMath_JUnit4 -Dtacoco.home=$(pwd) -Dtacoco.project=spiderMath_JUnit4 -Danalyzer.opts="configs/tacoco-analyzer.config"
+
+if [ $? -ne 0 ];
+then
+    echo "Tacoco failed with spiderMath_JUnit4..."
     exit 1
 fi
 
